### ISSUE TITLE
 no matches for projectriff.io/, Kind=Link

### ISSUE THREAD

**Issue by jtestard** [projectriff/go-function-invoker#13]
I have followed instructions from:

 - Here to install riff: https://projectriff.io/docs/getting-started-on-gke/
 - Here to install the `rot13` function: https://github.com/projectriff/go-function-invoker/tree/master/samples/rot13*

And now I receive this error message:

```
riff create go --input secrets --artifact rot13.so --handler Encode --push --useraccount ***
Initializing /home/docker/go/src/github.com/jtestard/go-function-invoker/samples/rot13/rot13-topics.yaml
Initializing /home/docker/go/src/github.com/jtestard/go-function-invoker/samples/rot13/rot13-function.yaml
Initializing /home/docker/go/src/github.com/jtestard/go-function-invoker/samples/rot13/rot13-link.yaml
Initializing /home/docker/go/src/github.com/jtestard/go-function-invoker/samples/rot13/Dockerfile
Building image ...
...
[STDOUT] 552783349336: Layer already exists
[STDOUT] 5ea538dd9f75: Layer already exists
[STDOUT] 6fa15c0fadea: Layer already exists
[STDOUT] 0f6f641d80ca: Layer already exists
[STDOUT] fbbeadfbd3ca: Layer already exists
[STDOUT] 06bc9900c10b: Layer already exists
[STDOUT] 76a66da94657: Layer already exists
[STDOUT] 0f3a12fef684: Layer already exists
[STDOUT] 0.0.1: digest: sha256:31aec1b99c36dfe2f2dbc2eaf12e9b418f101df8863c6a59dc5d6ce490283a87 size: 2217
Applying resources in .

error: unable to recognize "/home/.../go-function-invoker/samples/rot13/rot13-link.yaml": no matches for projectriff.io/, Kind=Link

exit status 1
```

*: with the exception that I used my Docker credentials to push an image to my docker hub and used the `--push` option of the `riff create go` command.

**Comment by jtestard** [comment]
I don't really understand what the concept of a link is, it seems to be missing from the documentation.

**Comment by trisberg** [comment]
Looks like you are using a snapshot build of the CLI against a v0.0.7 cluster, download the CLI binary from https://github.com/projectriff/riff/releases/tag/v0.0.7 and see if that works better. 

We recently introduced a Link resource, but you would have to instal the helm chart with `--devel` option to get the snapshot versions of the riff components deployed to the cluster

**Comment by trisberg** [comment]
You can use `riff version` to see the CLI and component versions

**Comment by scothis** [comment]
stale
