### ISSUE TITLE
Slim down docker image size

### ISSUE THREAD

**Issue by ericbottard** [projectriff/go-function-invoker#4]
Currently, the invoker image is built `FROM golang:x`, as attempts to use slimmer images (like alpine) failed due to go-plugin specific issues. Investigate

**Comment by dturanski** [comment]
I did some investigation.  Tried building invoker as a statically linked executable (and the function with and without static linking) to run on alpine.  e.g. `CGO_ENABLED=0 go build -a -o /riff-entrypoint cmd/${COMPONENT}.go` Ran into this https://github.com/golang/go/issues/19569.  Same result `plugin: not implemented`.
